"""Add image_url to products table

Revision ID: fc71da265a58
Revises: 44354e6e3450
Create Date: 2026-07-29 15:56:36.562001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc71da265a58'
down_revision: Union[str, Sequence[str], None] = '44354e6e3450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversations_name'), 'conversations', ['name'], unique=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'provider_id')
    op.drop_column('conversations', 'model_id')
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'is_deleted')
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=1)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('roles', sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
    op.add_column('roles', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=1)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=1)
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('products', 'image_url')
    op.add_column('conversations', sa.Column('model_id', sa.INTEGER(), nullable=False))
    op.add_column('conversations', sa.Column('provider_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'conversations', 'models', ['model_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'providers', ['provider_id'], ['id'])
    op.drop_index(op.f('ix_conversations_name'), table_name='conversations')
    # ### end Alembic commands ###
